__version__ = "0.1.5.6"

DEBUG = False
DEBUG_ESTCONNCOMPS = False
DEBUG_HINDSIGHT = False
DEBUG_IDASSIGNMENT = True
DEBUG_MOVIES = False
DEBUG_ANN = False
DEBUG_REPEATABLE_BEHAVIOR = False
DEBUG_BGBUFFER = False
DEBUG_TRACKINGSETTINGS = False
DEBUG_CHOOSEORIENTATIONS = True
USE_AVBIN = False
